export const REQUEST = (actionTypeName) => `${actionTypeName}_REQ`;
export const SUCCESS = (actionTypeName) => `${actionTypeName}_RESP`;
export const ERROR = (actionTypeName) => `${actionTypeName}_ERR`;

export const ACTION_TYPE = {
  FETCH_UNREAD_COUNT: 'NOTIFICATIONS_FETCH_UNREAD_COUNT',
  FETCH_RECENT: 'NOTIFICATIONS_FETCH_RECENT',
  FETCH_NOTIFICATIONS: 'NOTIFICATIONS_FETCH_NOTIFICATIONS',
  MARK_READ: 'NOTIFICATIONS_MARK_READ',
  MARK_ALL_READ: 'NOTIFICATIONS_MARK_ALL_READ',
  FETCH_PREFERENCES: 'NOTIFICATIONS_FETCH_PREFERENCES',
  SET_PREFERENCE: 'NOTIFICATIONS_SET_PREFERENCE',
};
